### ISSUE TITLE
Python 3 only?

### ISSUE THREAD

**Issue by unformatt** [indeedeng/django-ptrack#12]
Python 3 is not indicated anywhere in the README. But I see `typing` being used and get syntax errors in python 2.7.

**Comment by russelljk** [comment]
Yes the latest version is Python 3 only since official support for Python 2 has ended. If you have an older project you can use version 1.1.0 but you may miss out on Django 2.x support since both were added in v2 and up.

**Comment by cclauss** [comment]
I believe this issue can be closed.
