### ISSUE TITLE
Gif bytestring for py3

### ISSUE THREAD

**Issue by thenewguy** [indeedeng/django-ptrack#7]
ptrack returns invalid tracking pixel on py3.  Fixed by pr #6

**Comment by latimer1** [comment]
Hi @thenewguy, thanks for the issues and the pull request. I've been out of the office for the past week, will try to review these tickets hopefully in new few days.

**Comment by russelljk** [comment]
Sorry for any delay @thenewguy, I will verify this works on my end and get this issue merged & resolved.

**Comment by russelljk** [comment]
OK pull request is merged
